version: '3.9'

services:
  activemq:
    image: symptoma/activemq:latest
    container_name: activemq
    ports:
      - 1883:1883 # mqtt
      - 5672:5672 # amqp
      - 8161:8161 # ui
      - 61613:61613 # stomp
      - 61614:61614 # ws
      - 61616:61616 # jms
    volumes:
      - ~/Documents/data/activemq/data:/data/activemq
      - ~/Documents/data/activemq/log:/var/log/activemq
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=username
      - ACTIVEMQ_ADMIN_PASSWORD=password
    healthcheck:
      test: ['CMD', 'nc', '-vz', 'localhost', '8161']
      interval: 5s
      timeout: 5s
      retries: 5
