version: '3.9'

services:
  redis-instance:
    image: redis:latest
    container_name: redis-instance
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  redis-service:
    container_name: redis-service
    build:
      context: .
      no_cache: true
    expose:
      - 8080
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - KEY_CLOAK_EXPRESS_HOST=http://key-cloak-instance:8080/realms/express
    command: yarn dev
    depends_on:
      - redis-instance
