---
components:
  examples: {}
  headers: {}
  parameters: {}
  requestBodies: {}
  responses: {}
  schemas:
    CapitalPorfolio:
      properties:
        percentage:
          type: 'number'
          format: 'double'
        updatedDate:
          type: 'string'
        market:
          type: 'string'
        sector:
          type: 'string'
        stockCode:
          type: 'string'
        portfolioCode:
          type: 'string'
        capital:
          type: 'string'
        id:
          type: 'string'
      required:
        - 'percentage'
        - 'updatedDate'
        - 'market'
        - 'sector'
        - 'stockCode'
        - 'portfolioCode'
        - 'capital'
        - 'id'
      type: 'object'
      description: 'Model CapitalPorfolio'
    CapitalAvailableDates:
      properties:
        availableDate:
          type: 'string'
        portfolioCode:
          type: 'string'
        capital:
          type: 'string'
        id:
          type: 'string'
      required:
        - 'availableDate'
        - 'portfolioCode'
        - 'capital'
        - 'id'
      type: 'object'
      description: 'Model CapitalAvailableDates'
    StockHistory:
      allOf:
        - $ref: '#/components/schemas/CapitalPorfolio'
        - properties:
            percentageChange:
              type: 'number'
              format: 'double'
          required:
            - 'percentageChange'
          type: 'object'
    Todo:
      properties:
        completed:
          type: 'boolean'
        description:
          type: 'string'
        title:
          type: 'string'
        id:
          type: 'string'
        userId:
          type: 'string'
      type: 'object'
    CreateResponse:
      properties:
        acknowledged:
          type: 'boolean'
      required:
        - 'acknowledged'
      type: 'object'
    TodoRequestBody:
      properties:
        description:
          type: 'string'
        completed:
          type: 'boolean'
        title:
          type: 'string'
      required:
        - 'title'
      type: 'object'
    UpdateResponse:
      properties:
        upsertedCount:
          type: 'number'
          format: 'double'
        modifiedCount:
          type: 'number'
          format: 'double'
        matchedCount:
          type: 'number'
          format: 'double'
        acknowledged:
          type: 'number'
          format: 'double'
      required:
        - 'upsertedCount'
        - 'modifiedCount'
        - 'matchedCount'
        - 'acknowledged'
      type: 'object'
    DeleteResponse:
      properties:
        deletedCount:
          type: 'number'
          format: 'double'
        acknowledged:
          type: 'boolean'
      required:
        - 'deletedCount'
        - 'acknowledged'
      type: 'object'
    KeyCloakUserInfoResponse:
      properties:
        email:
          type: 'string'
        preferred_username:
          type: 'string'
        email_verified:
          type: 'boolean'
        sub:
          type: 'string'
      required:
        - 'email'
        - 'preferred_username'
        - 'email_verified'
        - 'sub'
      type: 'object'
    KeyCloakAddUserResponse:
      properties:
        requiredActions:
          items:
            type: 'string'
          type: 'array'
        lastName:
          type: 'string'
        groups:
          items:
            type: 'string'
          type: 'array'
        firstName:
          type: 'string'
        enabled:
          type: 'boolean'
        emailVerified:
          type: 'boolean'
        email:
          type: 'string'
      required:
        - 'requiredActions'
        - 'lastName'
        - 'groups'
        - 'firstName'
        - 'enabled'
        - 'emailVerified'
        - 'email'
      type: 'object'
    SignUpRequest:
      properties:
        password:
          type: 'string'
        username:
          type: 'string'
      required:
        - 'password'
        - 'username'
      type: 'object'
    KeyCloakTokenResponse:
      properties:
        scope:
          type: 'string'
        session_state:
          type: 'string'
        token_type:
          type: 'string'
        refresh_token:
          type: 'string'
        refresh_expires_in:
          type: 'number'
          format: 'double'
        expires_in:
          type: 'number'
          format: 'double'
        access_token:
          type: 'string'
      required:
        - 'scope'
        - 'session_state'
        - 'token_type'
        - 'refresh_token'
        - 'refresh_expires_in'
        - 'expires_in'
        - 'access_token'
      type: 'object'
    SignInRequest:
      properties:
        password:
          type: 'string'
        username:
          type: 'string'
      required:
        - 'password'
        - 'username'
      type: 'object'
  securitySchemes:
    tsoa_auth:
      type: 'oauth2'
      flows:
        implicit:
          authorizationUrl: 'http://swagger.io/api/oauth/dialog'
          scopes:
            write:pets: 'modify things'
            read:pets: 'read things'
info:
  title: '@starter/express'
  version: '1.0.0'
  description: 'Starter - Express'
  license:
    name: 'MIT'
  contact:
    name: 'hieudoanm '
    email: 'hieumdoan@gmail.com'
openapi: '3.0.0'
paths:
  /health:
    get:
      operationId: 'Get'
      responses:
        200:
          description: "Service's Status"
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: 'string'
                required:
                  - 'status'
                type: 'object'
      tags:
        - 'Health'
      security: []
      parameters: []
  /portfolio/{capital}/active-stock-codes:
    get:
      operationId: 'GetActiveStockCodes'
      responses:
        200:
          description: 'Ok'
          content:
            application/json:
              schema:
                items:
                  properties:
                    stockCode:
                      type: 'string'
                  required:
                    - 'stockCode'
                  type: 'object'
                type: 'array'
      tags:
        - 'Portfolio'
      security: []
      parameters:
        - in: 'path'
          name: 'capital'
          required: true
          schema:
            type: 'string'
  /portfolio/{capital}/{portfolioCode}:
    get:
      operationId: 'GetPortfolio'
      responses:
        200:
          description: 'Ok'
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CapitalPorfolio'
                type: 'array'
      tags:
        - 'Portfolio'
      security: []
      parameters:
        - in: 'path'
          name: 'capital'
          required: true
          schema:
            type: 'string'
        - in: 'path'
          name: 'portfolioCode'
          required: true
          schema:
            type: 'string'
        - in: 'query'
          name: 'updatedDate'
          required: true
          schema:
            type: 'string'
  /portfolio/{capital}/{portfolioCode}/available-dates:
    get:
      operationId: 'GetAvailableDates'
      responses:
        200:
          description: 'Ok'
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CapitalAvailableDates'
                type: 'array'
      tags:
        - 'Portfolio'
      security: []
      parameters:
        - in: 'path'
          name: 'capital'
          required: true
          schema:
            type: 'string'
        - in: 'path'
          name: 'portfolioCode'
          required: true
          schema:
            type: 'string'
  /portfolio/{capital}/{portfolioCode}/{stockCode}:
    get:
      operationId: 'GetStockHistory'
      responses:
        200:
          description: 'Ok'
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/StockHistory'
                type: 'array'
      tags:
        - 'Portfolio'
      security: []
      parameters:
        - in: 'path'
          name: 'capital'
          required: true
          schema:
            type: 'string'
        - in: 'path'
          name: 'portfolioCode'
          required: true
          schema:
            type: 'string'
        - in: 'path'
          name: 'stockCode'
          required: true
          schema:
            type: 'string'
        - in: 'query'
          name: 'fromDate'
          required: false
          schema:
            default: ''
            type: 'string'
        - in: 'query'
          name: 'toDate'
          required: false
          schema:
            default: ''
            type: 'string'
  /todos:
    get:
      operationId: 'GetTodos'
      responses:
        200:
          description: 'List of Todos'
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Todo'
                type: 'array'
      tags:
        - 'Todos'
      security:
        - jwt: []
      parameters: []
    post:
      operationId: 'CreateTodo'
      responses:
        201:
          description: 'New Todo'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateResponse'
      tags:
        - 'Todos'
      security:
        - jwt: []
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoRequestBody'
  /todos/{id}:
    get:
      operationId: 'GetTodo'
      responses:
        200:
          description: 'Get Todo by ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
      tags:
        - 'Todos'
      security:
        - jwt: []
      parameters:
        - in: 'path'
          name: 'id'
          required: true
          schema:
            type: 'string'
    patch:
      operationId: 'UpdateTodo'
      responses:
        200:
          description: 'Updated Todo'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateResponse'
      tags:
        - 'Todos'
      security:
        - jwt: []
      parameters:
        - in: 'path'
          name: 'id'
          required: true
          schema:
            type: 'string'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoRequestBody'
    put:
      operationId: 'PatchTodo'
      responses:
        200:
          description: 'Updated Todo'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateResponse'
      tags:
        - 'Todos'
      security:
        - jwt: []
      parameters:
        - in: 'path'
          name: 'id'
          required: true
          schema:
            type: 'string'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoRequestBody'
    delete:
      operationId: 'DeleteTodo'
      responses:
        200:
          description: 'Deleted Response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
      tags:
        - 'Todos'
      security:
        - jwt: []
      parameters:
        - in: 'path'
          name: 'id'
          required: true
          schema:
            type: 'string'
  /users/info:
    get:
      operationId: 'GetUserInfo'
      responses:
        200:
          description: 'User Info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyCloakUserInfoResponse'
      tags:
        - 'Users'
      security: []
      parameters: []
  /users/sign-up:
    post:
      operationId: 'SignUp'
      responses:
        201:
          description: 'New User Info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyCloakAddUserResponse'
      tags:
        - 'Users'
      security: []
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
  /users/sign-in:
    post:
      operationId: 'SignIn'
      responses:
        200:
          description: 'User Token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyCloakTokenResponse'
      tags:
        - 'Users'
      security: []
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
  /users/refresh-token:
    post:
      operationId: 'RefreshToken'
      responses:
        200:
          description: 'User Token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyCloakTokenResponse'
      tags:
        - 'Users'
      security: []
      parameters: []
  /users/sign-out:
    post:
      operationId: 'SignOut'
      responses:
        204:
          description: 'No Content'
      tags:
        - 'Users'
      security: []
      parameters: []
  /users/{id}/password:
    patch:
      operationId: 'ChangePassword'
      responses:
        204:
          description: 'No Content'
      tags:
        - 'Users'
      security: []
      parameters:
        - in: 'path'
          name: 'id'
          required: true
          schema:
            type: 'string'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                password:
                  type: 'string'
              required:
                - 'password'
              type: 'object'
  /api/vnindex/history/{symbol}/chart:
    get:
      operationId: 'ChartifyHistory'
      responses:
        200:
          description: 'Chart SVG'
          content:
            application/json:
              schema:
                type: 'number'
                enum:
                  - null
                nullable: true
      tags:
        - 'VNINDEX'
      security: []
      parameters:
        - in: 'path'
          name: 'symbol'
          required: true
          schema:
            type: 'string'
        - in: 'query'
          name: 'width'
          required: false
          schema:
            default: 500
            format: 'double'
            type: 'number'
        - in: 'query'
          name: 'height'
          required: false
          schema:
            default: 100
            format: 'double'
            type: 'number'
        - in: 'query'
          name: 'minValue'
          required: false
          schema:
            default: 0
            format: 'double'
            type: 'number'
        - in: 'query'
          name: 'maxValue'
          required: false
          schema:
            default: 200
            format: 'double'
            type: 'number'
        - in: 'query'
          name: 'strokeColor'
          required: false
          schema:
            default: '#0074d9'
            type: 'string'
        - in: 'query'
          name: 'strokeWidth'
          required: false
          schema:
            default: 2
            format: 'double'
            type: 'number'
servers:
  - url: '/'
