version: '3.9'

volumes:
  vault_data:
    driver: local

services:
  vault-instance:
    image: vault:latest
    container_name: vault-instance
    volumes:
      - vault_data:/vault/file
    ports:
      - '8200:8200'
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=07b165bf-74fc-4636-96aa-e5070c96f75f

  solana-service:
    container_name: solana-service
    build:
      context: .
    expose:
      - 8080
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
    command: yarn dev
