version: '3.9'

services:
  graphql-service:
    container_name: graphql-service
    build:
      context: .
    expose:
      - 5000
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
    command: yarn dev
