version: '3.9'

services:
  express-service:
    container_name: express-service
    build:
      context: .
      no_cache: true
    expose:
      - 8080
    ports:
      - '8081:8080'
    environment:
      - PORT=8080
    command: yarn dev
