version: '3.9'

services:
  vault-instance:
    image: vault:latest
    container_name: vault-instance
    ports:
      - '8200:8200'
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=07b165bf-74fc-4636-96aa-e5070c96f75f

  vault-service:
    container_name: vault-service
    build:
      context: .
      no_cache: true
    expose:
      - 8080
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
    command: yarn dev
