version: '3.9'

services:
  socket-service:
    container_name: socket-service
    build:
      context: .
      no_cache: true
    expose:
      - 8080
    ports:
      - '8085:8080'
    environment:
      - PORT=8080
      - KEY_CLOAK_EXPRESS_HOST=http://key-cloak-instance:8080/realms/express
    command: yarn dev
