#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn lint:apollo
yarn lint:elastic
yarn lint:express
yarn lint:hedera
yarn lint:kafka:producer
yarn lint:kafka:consumer
yarn lint:postgres
yarn lint:rabbit:producer
yarn lint:rabbit:consumer
yarn lint:redis:producer
yarn lint:redis:consumer
yarn lint:socket
yarn lint:solana
yarn pretty-quick --staged
