name: CI

on:
  push:
    branches:
      - master
      - develop
      - hotfix/**
      - feature/**
      - renovate/**

jobs:
  github-actions:
    strategy:
      fail-fast: false
      matrix:
        node:
          - name: Node.js 16
            version: 16.x
        os:
          - name: Ubuntu
            version: ubuntu-latest
        project:
          - name: APIs - Express
            working-directory: ./apis/express
          - name: Connections - Socket.io
            working-directory: ./connections/socket
          - name: GraphQL - Apollo
            working-directory: ./graphql/apollo
          - name: Messages - ActiveMQ - Producer
            working-directory: ./messages/active/producer
          - name: Messages - ActiveMQ - Consumer
            working-directory: ./messages/active/consumer
          - name: Messages - Kafka - Producer
            working-directory: ./messages/kafka/producer
          - name: Messages - Kafka - Consumer
            working-directory: ./messages/kafka/consumer
          - name: Messages - RabbitMQ - Producer
            working-directory: ./messages/rabbit/producer
          - name: Messages - RabbitMQ - Consumer
            working-directory: ./messages/rabbit/consumer
          - name: Messages - Redis - Producer
            working-directory: ./messages/redis/producer
          - name: Messages - Redis - Consumer
            working-directory: ./messages/redis/consumer
    name: ${{ matrix.os.name }} - ${{ matrix.node.name }} - ${{ matrix.project.name }}
    runs-on: ${{ matrix.os.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node.version }}
      - name: Install Dependencies
        run: yarn install --network-timeout 86400000
        working-directory: ${{ matrix.project.working-directory }}
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
      - name: Build Production
        run: yarn build
        working-directory: ${{ matrix.project.working-directory }}
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
      - name: Unit Test
        run: yarn test
        working-directory: ${{ matrix.project.working-directory }}
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
