name: CI

on:
  push:
    branches:
      - master
      - develop
      - hotfix/**
      - feature/**
      - renovate/**

jobs:
  github-actions:
    strategy:
      fail-fast: false
      matrix:
        node:
          - name: Node.js 16
            version: 16.x
        os:
          - name: Ubuntu
            version: ubuntu-latest
        project:
          - name: Contract - Hedera
            working-directory: ./contracts/hedera-starter
          - name: Contract - Solana
            working-directory: ./contracts/solana-starter
          - name: Database - Elastic
            working-directory: ./databases/elastic-starter
          - name: Database - PostgreSQL
            working-directory: ./databases/postgres-starter
          - name: Apollo
            working-directory: ./services/apollo-starter
          - name: Express
            working-directory: ./services/express-starter
          - name: Socket.io
            working-directory: ./services/socket-starter
    name: ${{ matrix.os.name }} - ${{ matrix.node.name }} - ${{ matrix.project.name }}
    runs-on: ${{ matrix.os.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node.version }}
      - name: Install Dependencies
        run: yarn install --network-timeout 86400000
        working-directory: ${{ matrix.project.working-directory }}
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
      - name: Build Production
        run: yarn build
        working-directory: ${{ matrix.project.working-directory }}
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
      - name: Unit Test
        run: yarn test
        working-directory: ${{ matrix.project.working-directory }}
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
