name: Docker

on:
  push:
    branches:
      - master
      - develop

jobs:
  github-actions:
    strategy:
      fail-fast: false
      matrix:
        node:
          - name: Node.js 16
            version: 16.x
        os:
          - name: Ubuntu
            version: ubuntu-latest
        project:
          - name: Contract - Hedera
            image-name: hedera-starter
            working-directory: ./contracts/hedera-starter
          - name: Contract - Solana
            image-name: solana-starter
            working-directory: ./contracts/solana-starter
          - name: Database - Elastic
            image-name: elastic-starter
            working-directory: ./databases/elastic-starter
          - name: Database - PostgreSQL
            image-name: postgres-starter
            working-directory: ./databases/postgres-starter
          - name: Messaging - Kafka - Producer
            image-name: kafka-producer-starter
            working-directory: ./messages/kafka-starter/producer
          - name: Messaging - Kafka - Consumer
            image-name: kafka-consumer-starter
            working-directory: ./messages/kafka-starter/consumer
          - name: Messaging - Rabbit - Producer
            image-name: rabbit-producer-starter
            working-directory: ./messages/rabbit-starter/producer
          - name: Messaging - Rabbit - Consumer
            image-name: rabbit-consumer-starter
            working-directory: ./messages/rabbit-starter/consumer
          - name: Messaging - Redis - Producer
            image-name: redis-producer-starter
            working-directory: ./messages/redis-starter/producer
          - name: Messaging - Redis - Consumer
            image-name: redis-consumer-starter
            working-directory: ./messages/redis-starter/consumer
          - name: Apollo
            image-name: apollo-starter
            working-directory: ./graphql/apollo-starter
          - name: Express
            image-name: express-starter
            working-directory: ./services/express-starter
          - name: Socket.io
            image-name: socket-starter
            working-directory: ./services/socket-starter
    name: ${{ matrix.os.name }} - ${{ matrix.node.name }} - ${{ matrix.project.name }}
    runs-on: ${{ matrix.os.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Branch
        run: echo ${{ github.head_ref || github.ref_name }}
      - name: TimeZone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Ho_Chi_Minh'
      - name: Get Date & Time
        id: datetime
        run: |
          echo $(date +'%Y-%m-%dT%H:%M:%S')
          echo "::set-output name=datetime::$(date +'%Y%m%d.%H%M%S')"
      - name: Get Commit SHA
        id: version
        run: |
          echo $(git rev-parse --short HEAD)
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Update Tools
        run: sudo apt-get update && sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
      - name: Add Repository
        run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      - name: Install Docker
        run: sudo apt-get update && sudo apt-get install docker-ce
      - name: Docker Build
        working-directory: ${{ matrix.project.working-directory }}
        run: docker build . --no-cache -t ${{ matrix.project.image-name }}:$IMAGE_TAG
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
          IMAGE_TAG: ${{ github.head_ref || github.ref_name }}.${{ steps.datetime.outputs.datetime }}.${{ steps.version.outputs.sha_short }}
