name: packages

on:
  push:
    branches:
      - master
    paths:
      - packages/**

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Ubuntu
            version: ubuntu-latest
        node:
          - name: Node.js 16
            version: 16.x
        package:
          - name: Package - apollo
            working-directory: ./packages/apollo
          - name: Package - axios
            working-directory: ./packages/axios
          - name: Package - dotenv
            working-directory: ./packages/dotenv
          - name: Package - download
            working-directory: ./packages/download
          - name: Package - elasticsearch
            working-directory: ./packages/elasticsearch
          - name: Package - fast
            working-directory: ./packages/fast
          - name: Package - football
            working-directory: ./packages/football
          - name: Package - forex
            working-directory: ./packages/forex
          - name: Package - jwt
            working-directory: ./packages/jwt
          - name: Package - mongodb
            working-directory: ./packages/mongodb
          - name: Package - news
            working-directory: ./packages/news
          - name: Package - pino
            working-directory: ./packages/pino
          - name: Package - redis
            working-directory: ./packages/redis
          - name: Package - telegram
            working-directory: ./packages/telegram
          - name: Package - utils
            working-directory: ./packages/utils
          - name: Package - vault
            working-directory: ./packages/vault
          - name: Package - weather
            working-directory: ./packages/weather
    name: ${{ matrix.os.name }} - ${{ matrix.node.name }} - ${{ matrix.package.name }}
    runs-on: ${{ matrix.os.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node.version }}
          registry-url: https://npm.pkg.github.com/
      - name: Install Dependencies
        run: yarn install --no-cache --network-timeout 86400000
        working-directory: ${{ matrix.package.working-directory }}
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
      - name: Unit Test
        run: yarn test
        working-directory: ${{ matrix.package.working-directory }}
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
      - name: Build Package
        run: yarn build
        working-directory: ${{ matrix.package.working-directory }}
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
      - name: Publish Package
        run: yarn publish
        working-directory: ${{ matrix.package.working-directory }}
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_TOKEN }}
